### ISSUE TITLE
Feat: Timer scene 화면 전환 - 바텀 시트

### ISSUE THREAD

**Issue by GangWoon** [ToDo-Garden/ToDo-Garden#277]
#229 

### 🛠️ 진행할 작업

타이머 신에서 발생하는 화면 전환 구현

### 📝 TODO
- [ ] 바텀 시트 전환 구현

바텀시트 요구사항
- 최소 시간 설정 (10분)
- 비정상적인 Date 값 (우선순위 높음)
- 뷰 배치
<img width="376" alt="Screenshot 2024-06-28 at 16 23 49" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/48466830/7e9503f9-2e3c-43d3-873f-6c9835a562bc">
<img width="269" alt="Screenshot 2024-06-28 at 16 24 06" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/48466830/0e0b2000-bd6f-4dd7-a5d5-3a96cfbfbf23">

### 🗂️ 백로그

- 링크:

**Comment by GangWoon** [comment]
@HG-SONG 
SettingTimeView를 요구사항에 맞게 수정해야할 거 같습니다.
제가 작업을 진행하는게 좋을까요? 울버린이 수정하시는게 편하신가요?

**Comment by HG-SONG** [comment]
@GangWoon 
각 요구사항에 대한 디테일들만 짚어주시면 제가 해보도록 하겠습니다! 
일단 제가 지금 당장 생각해본 것들입니다. 보완할 부분이 있다면 알려주세요. 

### 최소 시간 설정 (10분)
- 말그대로 설정가능한 최소시간을 10분으로 제한 -> 10분 미만의 시간이 선택될 경우 버튼 disable 
- 초기상태 "10분"  설정 

### 비정상적인 Date 값 (우선순위 높음)
- 협의한 시간관련 포맷 기반으로 변경 (3600 == 1시간) 
++ "정상적 Date값" 의 조건이 위 내용이 아니라면 "정상적 Date값"의 예시 요청드립니다. 

### 뷰 배치
- 버튼의 topAnchor위치 변경

**Comment by GangWoon** [comment]
@HG-SONG 
1. 비정상적인 Date값
0시 3분 0초를 입력했을 때  아래와 같이 나오게 됩니다.

2024-06-28 08:33:16 +0000
17h 33min 16sec
-> 63196.0 (Double)

2.뷰 배치
디자이너 분하고 실사이즈에 대해서 더 정확하게 얘기를 나눠야지 될 거 같습니다.
현재 제가 눈으로 봤을 때 아래 구조 사이 패딩 값이 명확하지 못한 거 같습니다.
(구조) 집중시간 설정 - 셀렉터 - 버튼

**Comment by HG-SONG** [comment]
@GangWoon 
아하 비 정상적인 Date값의 의미가 그것이었군요. 

0시 3분 0초를 입력하면 
협정세계시( 국제표준시 ) 를 기준으로 정확히 3분을 더한 `시각` 이 반환되게끔 했던 기억이 있네요. 
협정세계시에 + 9 시간을 더하면 한국 시간이 되는걸로 알고있습니다. 

즉, 강운께서 보신 `2024-06-28 08:33:16 +0000` 는 한국시간 17:30:16 에 3분을 더한 시간이죠. 
의도한건 아니고 단지 후처리(?)를 하지 않았을 뿐입니다. 
후처리를 통해 한국 시각으로 고정을 시킬까 하다가, 시간에 대해 정해진게 없어서 그냥 날것으로 놔뒀습니다. 

SettingTimeView.calculateDate() 메소드를 통해 얻어지는 `date`가 어떤식이길 원하시나요? 

```swift
#if DEBUG
@available(iOS 17.0, *)
#Preview {
  let button = ToDoGardenBoxButton(title: "asdasd", buttonType: .primaryRoundRectButton)
  
  let view = SettingTimeView(with: button, for: .breakTimeSetting)
  
  let action = UIAction { _ in
    view.calculateDate { date in print(date) }
  }
  
  button.addAction(action, for: .touchUpInside)
  return view
}
#endif
```

**Comment by GangWoon** [comment]
SettingTimeView.calculateDate()를 통해서 전달되는 값을 Dobule로 전환하시는건 어떠신가요?

`SettingTimeView.calculateDate()` -> `SettingTimeView.transformSeconds() ` 해당 화면 이후에 모든 화면에서 공통된 시간초를 사용할 수 있도록 구현하면 좋을 거 같습니다 :)
