### ISSUE TITLE
Bug: ToDoGardenAlertControllerDelegate 적절하지 않는 데이터 전달

### ISSUE THREAD

**Issue by GangWoon** [ToDo-Garden/ToDo-Garden#315]
## issue 1: `func handleButtonAction(_ buttonType:)`
**ToDoGardenAlertControllerDelegate.handleButtonAction** 으로 전달 받는 데이터와 뷰에서 보여지는 데이터가 일치하지 않습니다.
<img width="415" alt="Screenshot 2024-07-08 at 15 23 36" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/48466830/581e4183-30d4-4618-8088-8d00b379c654">

Case 1, 2: 포기하기 눌렀을 때
Case 3: 집중하기 눌렀을 때
<img width="235" alt="Screenshot 2024-07-08 at 15 23 52" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/48466830/f9e21e93-bb7e-436f-b118-ecba213ba3d2">
원하는 결과: 신뢰할 수 있는 델리게이트

##issue 2: 알럿이 생성될 때 디밍 뷰(검은 색 뷰)가 올라오는게 보여짐.
원하는 결과: 알럿 뷰는 어떻게 올라오는지 상관 없으나 디밍 뷰는 올라오는게 아닌, 서서히 딤됐으면 좋겠습니다.

### 📝 TODO

- [ ]

### 🧨 관련 버그 트리아지

- 링크:

**Comment by GangWoon** [comment]
@HG-SONG 
isuue - 1해당 작업에 대해서 진행해주실 수 있을까요?

---

issue - 2 디밍뷰 관련해서는 제가 작업해보고 싶은데 진행해도 괜찮을까요??

**Comment by HG-SONG** [comment]
@GangWoon 
### issue 1: 집중하기 관련 

아마도 아래와 같은 동작을 기대하셨을 것 같습니다.

![스크린샷 2024-07-08 오후 4 44 22](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/3ee5bfec-fc0a-47be-b567-e3946ad7a86b)

하지만 실제 동작은 아래와 같죠 
![스크린샷 2024-07-08 오후 4 54 18](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/472e7ec4-6fbb-4485-b361-c73bda39b48d)

저는 이렇게 생각했습니다. 
집중하고 있는 상황에서 집중을 그만두고자 하여 "그만할래?" 알럿이 떴을 때, "더 집중할래" 는 사실상 취소 (cancel, back)와 같다.
ButtonActionType에 대한 구분 기준은 아래와 같습니다. 

```swift
  func handleButtonAction(_ buttonType: ToDoGardenUIConstant.Constant.ToDoGardenAlertView.Content.ButtonActionType) {
    switch buttonType {

    case .cancel :
      print("단순히 모달을 다시 내리기만 하면 되는 작업")
    case .keepConcentration:
      print("집중/휴식시간이 끝나거나 휴식시간 도중 집중시간을 재설정하는 등 집중시간을 시작/연장하기위한 추가적인 작업")
  
    default : break
    }
  }
```

혼란을 피하기 위한 구분이었는데, 오히려 더 혼란을 가중시킨 느낌이네요. 
저의 의도를 아신 지금 아래 사진을 다시 보셨을때, 여전히 이상한가요? 
<img width="249" alt="스크린샷 2024-07-08 오후 5 10 53" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/dac3ee3f-f66a-43de-a0fa-021573dc7efe">


### issue 2: 디밍 뷰 

이건 변명의 여지없습니다. ㅋ..
일단 이대로 개발 진행해주시고 제가 후다닥 고쳐서 수정본 머지시키겠습니다. 

를 작성하는 중이었는데 

> issue - 2 디밍뷰 관련해서는 제가 작업해보고 싶은데 진행해도 괜찮을까요??

이 코멘트가 달렸네요. 그래주시면 감사합니다 !@ 이슈 1에 대한 답변 기다리겠습니다

**Comment by GangWoon** [comment]
@HG-SONG 
말씀하신대로 작성한 부분을 보면 이해가 됩니다 :)
제가 해당 코드를 이해하는데 혼란이 왔던 부분에 대해서 조금더 자세하게 말씀드리자면
Case가 도메인에 대한 내용을 담고 있었지만, cancel은 도메인이 아닌, 뷰 동작에 대한 내용을 담고 있었기 때문입니다.

코드에 대한 의도를 파악했기 때문에 추가적인 작업은 필요 없어보입니다 :) 
감사합니다.

**Comment by HG-SONG** [comment]
이슈 1 에 대하여 추가 코멘트 남깁니다. 

아무래도 매우 혼란을 유발하는 느낌이 이제와서 듭니다. 회생방안 적어봅니다. 

1. cancel의 이름을 dismissModal로 변경

어떤가요 ?

**Comment by HG-SONG** [comment]
@GangWoon
